name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: ""
    strategy:
      matrix:
        ruby-version: ['3.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run Standard
        run: bundle exec standardrb

      - name: Run RSpec
        run: bundle exec rspec --format documentation
